//------------------------------------------------------------------//
//                      Even Fibonacci numbers                      //
//            Each new term in the Fibonacci sequence is            //
//          generated by adding the previous two terms. By          //
//        starting with 1 and 2, the first 10 terms will be:        //
//------------------------------------------------------------------//

#include <iostream>
#include <string>

using namespace std;

int even_fibonacci_number(int num);

int main(int argc, char *argv[]) {
  if (argc > 0) {
    int even_fib_num = even_fibonacci_number(stoi(argv[1]));
    cout << fib_num << endl;
  } else
    throw "Please Enter Params";

  return 0;
}

int even_fibonacci_number(int num){
  int t1 = 1, t2 = 2, nxtItem = 0;
  while (num--)
  {
    if (num < 0)
      break;
    nxtItem = t1 + t2;
    t1 = t2;
    t2 = nxtItem;
  }
}
