//------------------------------------------------------------------//
//                      Even Fibonacci numbers                      //
//            Each new term in the Fibonacci sequence is            //
//          generated by adding the previous two terms. By          //
//        starting with 1 and 2, the first 10 terms will be:        //
//              1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...              //
//        By considering the terms in the Fibonacci sequence        //
//        whose values do not exceed four million, find the         //
//                  sum of the even-valued terms.                   //
//------------------------------------------------------------------//


#include <iostream>
#include <string>
#include <vector>

using namespace std;

long long int even_fibc_nums();

int main(int argc, char *argv[]) {
  if (argc > 0) {
    // argv[1]
    cout << even_fibc_nums() << endl;
  } else
    throw "Please Enter Params";

  return 0;
}

long long int even_fibc_nums(){
  long long int t1 = 1, t2 = 2, nxtItem = 0, sum = 2;
  while (nxtItem < 4000000)
  {
    nxtItem = t1+t2;
    t1 = t2;
    t2 = nxtItem;
    if (nxtItem % 2 == 0) sum += nxtItem;
  }
  return sum;
}
